### ISSUE TITLE
Questions about real-world experiments.

### ISSUE THREAD

**Issue by Galaxies99** [PKU-HMI-Lab/LIFT3D#1]
Hi,

I have a few questions regarding the real-world experiments.

1. In the paper, it is mentioned that Lift3D is a keyframe-based policy, in contrast to continuous policies like DP or DP3. How are the keyframes extracted from demonstration videos, particularly in real-world demonstrations? Is the keyframe discovery process the same as those used in methods like PerAct or RVT?

2. For tasks involving continuous actions (e.g., watering plants, wiping a table, or sliding a block as described in the paper):
- How are keyframes defined for such tasks? For instance, in the sliding block task, the sliding process seems to be continuous—how is a keyframe determined along a continuous trajectory?
- Could you provide more examples of keyframe extraction for these tasks to aid in reproducing similar experiments?

3. From Fig.4 in the paper, I observe that the tabletop is manually cropped off from the point cloud. Is this cropping step essential, or is it acceptable to retain the tabletop points while only cropping points outside the predefined workspace?

4.  Regarding the camera in real-world experiments.
- Does the specific model of the RGB-D camera (e.g., L515) significantly affect performance?
- Is it possible to replace the L515 with a D435 or D415, given that the L515 is no longer supported by Intel?

**Comment by liujiaming1996** [comment]
> Hi,
> 
> I have a few questions regarding the real-world experiments.
> 
> 1. In the paper, it is mentioned that Lift3D is a keyframe-based policy, in contrast to continuous policies like DP or DP3. How are the keyframes extracted from demonstration videos, particularly in real-world demonstrations? Is the keyframe discovery process the same as those used in methods like PerAct or RVT?
> 2. For tasks involving continuous actions (e.g., watering plants, wiping a table, or sliding a block as described in the paper):
> 
> * How are keyframes defined for such tasks? For instance, in the sliding block task, the sliding process seems to be continuous—how is a keyframe determined along a continuous trajectory?
> * Could you provide more examples of keyframe extraction for these tasks to aid in reproducing similar experiments?
> 
> 3. From Fig.4 in the paper, I observe that the tabletop is manually cropped off from the point cloud. Is this cropping step essential, or is it acceptable to retain the tabletop points while only cropping points outside the predefined workspace?
> 4. Regarding the camera in real-world experiments.
> 
> * Does the specific model of the RGB-D camera (e.g., L515) significantly affect performance?
> * Is it possible to replace the L515 with a D435 or D415, given that the L515 is no longer supported by Intel?

Thank you for your interest in our work! Below are our responses to your questions:

A1. Our proposed method is capable of supporting both dense frame closed-loop experiments (e.g., MetaWorld) and sparse key frame closed-loop experiments (e.g., RLBench). In our real-world experiments, we employ a rule-based approach for key frame extraction, similar to PerAct. However, we introduce additional constraints on the position or rotation angle of the 7 DoF pose during key frame extraction.

A2. Following PerAct and RVT, many tasks in RLBench (e.g., watering plants, sliding blocks, opening drawers, etc.) can be defined using key frames. The key frame description can be found in Appendix (A.2). We will release our real-world training dataset and key frame extraction code in the future. If you are in urgent need, you can refer to the key frame extraction code in PerAct.

A3. We followed the point cloud processing manner from DP3. We also tried "only cropping points outside the predefined workspace," and our method still works due to the large-scale pretrained knowledge and strong robotic 3D representation.


A4. In our experiments, we used the RealSense L515 RGBD camera, but it is also possible to use the D435 or other RGBD cameras. The choice of camera does not significantly impact the model's performance as long as the depth data is relatively complete.

**Comment by Galaxies99** [comment]
Thank you for your answer! 

I will try to train and deploy the policy in a real-world robot platform. Therefore, I wonder if it is possible to use dense control in the real world (If so, no additional keyframe annotations are needed).

Also, just to clarify, since DP3 claims that D435 produces a point cloud of _much worse quality_ than L515 (however I am pretty sure that the produced point cloud is relatively complete), I just want to confirm that using D415/D435 will not affect the policy performance heavily.

**Comment by liujiaming1996** [comment]
> Thank you for your answer!
> 
> I will try to train and deploy the policy in a real-world robot platform. Therefore, I wonder if it is possible to use dense control in the real world (If so, no additional keyframe annotations are needed).
> 
> Also, to clarify, since DP3 claims that D435 produces a point cloud of _much worse quality_ than L515 (however I am pretty sure that the produced point cloud is still relatively complete), I just want to confirm that using D415/D435 will not affect the policy performance heavily.

If conducting real-world experiments, we recommend adding a validation strategy during training, similar to OpenVLA, to measure the distance between the predicted pose and the GT pose.
We have conducted some preliminary experiments, and the D435 camera meets the requirements for real-world experiments. We hope this can be helpful for your research.

**Comment by Galaxies99** [comment]
Yeah definitely we will first validate the policy before deployment. Thank you again for your suggestions.
