### ISSUE TITLE
Question of Training Time

### ISSUE THREAD

**Issue by J-X-Chen** [PKU-HMI-Lab/LIFT3D#2]
Hello, Could I ask you the minimum requirements for a GPU and the corresponding training time?

**Comment by liujiaming1996** [comment]
> Hello, Could I ask you the minimum requirements for a GPU and the corresponding training time?

Thank you for your interest in our work. Our Lift3D policy’s two-stage training does not require many training resources. For Stage 1 (implicit 3D robotic representation learning), we need A100 GPUs for MAE self-supervised training, but only a few epochs are required since our base foundation model has undergone large-scale pretraining. For Stage 2 (explicit 3D robotic imitation learning), we can complete the training using just one 4090/3090 GPU, with an approximate training time of 1 hour per task, although this depends on the number of demonstrations used as training data.

**Comment by J-X-Chen** [comment]
Thank you!
